tabs:
  - name: "基本设置"
    key: "basic"
    items:
      - key: "IPCRecord"
        name: "备案号"
        type: "input"
        placeholder: ""
      - key: "telegram"
        name: "telegram"
        type: "input"
        placeholder: "只需填入 telegram 用户名即可"
      - key: "github"
        name: "github"
        type: "input"
        placeholder: "只需填入 github 用户名即可"
      - key: "mail"
        name: "邮箱"
        type: "input"
      - key: "payQRCode"
        name: "收款二维码"
        type: "image"
      - key: "hobbies"
        name: "footer 打字机后缀"
        type: "tags"
        default: "旅游;健身;阅读"
